services:
  lachiwa_cli:
    build: .
    image: lachiwa
    container_name: lachiwa_cli
    depends_on:
      - redis
    volumes:
      - ./honeytokens:/usr/src/app/honeytokens
    environment:
      - TERM=xterm-256color
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: python lachiwa_cli.py tui
