services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    #command: redis-server --appendonly yes  # Keep Redis running continuously

  lachiwa_cli:
    build: .
    image: lachiwa
    container_name: lachiwa_cli
    depends_on:
      - redis
    volumes:
      - ./honeytokens:/usr/src/app/honeytokens
    environment:
      - TERM=xterm-256color
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    #    stdin_open: true
    #    tty: true
    command: python lachiwa_cli.py tui
  
  lachiwa_sv:
    build: .
    image: lachiwa
    container_name: lachiwa_sv
    depends_on:
      - redis
    volumes:
      - ./alerts:/usr/src/app/alerts
    environment:
      - FLASK_APP=server.py
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0


volumes:
  redis-data:

